name = "code.lengstorf"
license = "ISC"
source_repo = "https://github.com/jlengstorf/code.lengstorf.com"
description = "An ultra-minimal theme for posting code stuff."
tags = [
  "blog",
  "code",
]
features = [
  "manual",
]
